-- Date: 2009-07-01
-- Time: 08:36:55
-- Rev.: 27

DROP TABLE IF EXISTS `creature_ai_texts2`;
CREATE TABLE IF NOT EXISTS `creature_ai_texts2` (
  `entry` mediumint(8) NOT NULL,
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  `sound` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `language` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote` smallint(5) unsigned NOT NULL DEFAULT '0',
  `comment` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Script Texts';

INSERT INTO `creature_ai_texts2` (`entry`, `sound`, `type`, `language`, `emote`, `comment`, `content_default`, `content_loc1`, `content_loc8`) SELECT `entry`, `sound`, `type`, `language`, `emote`, `comment`, `content_default`, `content_default` AS `content_loc1`, `content_default` AS `content_loc8` FROM `creature_ai_texts`;

DROP TABLE IF EXISTS `creature_ai_texts`;
RENAME TABLE `creature_ai_texts2` TO `creature_ai_texts`;

UPDATE `creature_ai_texts` SET `content_loc8` = 'Я привык работать для Великого инквизитора Изиллиена! Ваша мысль немного огорчила меня среди бела дня!' WHERE `entry` = -565;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я розскажу вам все! ОСТАНОВИТЕСЬ! ПОЖАЛУЙСТА!' WHERE `entry` = -555;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Приветствую, гражданин.' WHERE `entry` = -552;
UPDATE `creature_ai_texts` SET `content_loc8` = 'зовет на помощь!' WHERE `entry` = -551;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Охрана!' WHERE `entry` = -549;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ааааа... Охрана!' WHERE `entry` = -548;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Обнаружена неизвесная форма жизни... доступ...' WHERE `entry` = -547;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Покажи свою ярость!' WHERE `entry` = -542;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы тоже должны служить!' WHERE `entry` = -541;
UPDATE `creature_ai_texts` SET `content_loc8` = 'становится ОЧЕНЬ голодным!' WHERE `entry` = -540;
UPDATE `creature_ai_texts` SET `content_loc8` = 'становится голодным!' WHERE `entry` = -539;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Примените контрмеры. Отразите нападение нарушителей.' WHERE `entry` = -538;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы были обнаружены. Вы будете поглощены или устранены.' WHERE `entry` = -537;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Внимание! Внимание! Тревога нарушители! Тревога нарушители!' WHERE `entry` = -536;
UPDATE `creature_ai_texts` SET `content_loc8` = 'мы можем снять с вас проклятие, у нас есть технологии' WHERE `entry` = -535;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Плоть слаба. Мы сделаем вас лучше, более сильными... быстрыми.' WHERE `entry` = -534;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы - Мехагномы... сопротивление бесполезно.' WHERE `entry` = -533;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Остановитесь! Глупый C$, мы не позволим вам вызвать Мизраэль!' WHERE `entry` = -532;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Получите! Сухоусы одержат победу!' WHERE `entry` = -531;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет! Оставьте нас! Мы не должны провалить нашу миссию!' WHERE `entry` = -530;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Твердо стойте, братья. И не волнуйтесь! Мы превосходим по количеству!' WHERE `entry` = -529;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Умрите! Вы не освободите Мизраэля!' WHERE `entry` = -528;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Великий раздавит вас!' WHERE `entry` = -527;
UPDATE `creature_ai_texts` SET `content_loc8` = 'призывает Ветерана легиона Чернорука в помощь себе!' WHERE `entry` = -526;
UPDATE `creature_ai_texts` SET `content_loc8` = 'призывает Ткача ужаса из легиона Чернорука в помощь себе!' WHERE `entry` = -525;
UPDATE `creature_ai_texts` SET `content_loc8` = 'начинает призывать Ветерана легиона Чернорука!' WHERE `entry` = -524;
UPDATE `creature_ai_texts` SET `content_loc8` = 'начинает призывать Ткача ужаса из легиона Чернорука!' WHERE `entry` = -523;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Интересно, что Эрнестуэй даст мне для вашей шкуры!' WHERE `entry` = -522;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это станет телятиной сегодня вечером!' WHERE `entry` = -521;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эрнестуэй разориться, если он продолжит это! Лейн вероятно понятия не имеет, что он делает!' WHERE `entry` = -520;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Бросьте это, небольшое животное!' WHERE `entry` = -519;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Еще всего пятьдесят копыт и у меня будет новое оружие!' WHERE `entry` = -518;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет пути! Шлем головы носорога за очень низкую цену тридцати голов носорога? Я возьму два по тем ценам!' WHERE `entry` = -517;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Теперь ЭТО - спорт!' WHERE `entry` = -516;
UPDATE `creature_ai_texts` SET `content_loc8` = 'УБИТЬ УБИТЬ УБИТЬ!!!!!!!!!' WHERE `entry` = -515;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я уверен что Хеминг может что-нибудь сделать с вашими костями!' WHERE `entry` = -514;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы пытаетесь оглушить меня? Жалостный... Подождите... Что это это за звук?' WHERE `entry` = -513;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Када ну беттека, оч!' WHERE `entry` = -512;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эту Магмозрегар, ча!' WHERE `entry` = -511;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Каганишу!' WHERE `entry` = -510;
UPDATE `creature_ai_texts` SET `content_loc8` = 'КАГАНИШУ!' WHERE `entry` = -509;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кто смеет прерывать мою работу!? Покажи себя, трус!' WHERE `entry` = -508;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Каково значение этого волнения?!' WHERE `entry` = -507;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Приведите мне больше заключенных! Не отдыхайте, пока Азерот не будет очищен от беззаботных волшебников!' WHERE `entry` = -506;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эти тюрьмы должны быть заполнены немедленно, или Малигос узнает!' WHERE `entry` = -505;
UPDATE `creature_ai_texts` SET `content_loc8` = 'теперь может быть пойман.' WHERE `entry` = -504;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Дела идут как запланировано, Лорд Фалконкрест. Я уверяю вас, это - только вопрос времени.' WHERE `entry` = -503;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я предполагаю, что вы пришли с хорошими новостями?' WHERE `entry` = -502;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы мне наскучили. Прочь!' WHERE `entry` = -501;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Скажите Империану, что я рассмотрю предложение о прекращении военных действий. Но сначала, Вспеннер должна остановить его водные посягательства на мое повышение!' WHERE `entry` = -500;
UPDATE `creature_ai_texts` SET `content_loc8` = 'СТОП!' WHERE `entry` = -499;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кто смеет?' WHERE `entry` = -498;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы не можете остановить нас всех!' WHERE `entry` = -497;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваша смерть скоро вас настигнет....' WHERE `entry` = -496;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я - Хранитель Ключей. Действительно ли вы - Привратник?' WHERE `entry` = -495;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я освобожден! Спасибо.' WHERE `entry` = -494;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Смерть будет только началом вашей пытки.' WHERE `entry` = -493;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы не из моих. Король Мргл-Мргл, должно быть, послал вас, чтобы обговорить срок сдачи. Подъезжайте ближе, так чтобы я смог вас разглядеть.' WHERE `entry` = -492;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Отец мурлоку сыну, муж мурлок-жены' WHERE `entry` = -491;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Какая крошечная закуска идет в этом направлении? Я думаю это не один из мурлоков..' WHERE `entry` = -490;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Избавьте меня от своего присутствия. Вы были бы мудры, не появляясь в пределах моего зрения в будущем.' WHERE `entry` = -489;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я... подчиняюсь. Пока Шкварчун не согласится прекратить терроризировать мое племя, я не соглашусь на перемирие.' WHERE `entry` = -488;
UPDATE `creature_ai_texts` SET `content_loc8` = 'СТОЙ... НЕ НАДО БОЛЬШЕ!' WHERE `entry` = -487;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сила Шшератуса является нашей. Теперь все будут сокрушены энергией Драккари!!' WHERE `entry` = -486;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сделайте большой глоток мои братья!' WHERE `entry` = -485;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Убейте этих захватчиков, которые смеют осквернять наш алтарь!' WHERE `entry` = -484;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я уничтожу Рыцарей Серебряного Авангарда! Я сокрушу Плеть!' WHERE `entry` = -483;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Прикончите их, и затем мы двинемся на юг, чтобы убить их братьев!' WHERE `entry` = -482;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Они смеют нападать на нас? Дураки! Разве они не знают, что мы теперь всесильны?!' WHERE `entry` = -481;
UPDATE `creature_ai_texts` SET `content_loc8` = 'С силой диких богов, текущей в наших венах, никто, даже Король-лич, не может стоять на нашем пути!' WHERE `entry` = -480;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я вижу тебя, насекомое! Подходи ближе' WHERE `entry` = -479;
UPDATE `creature_ai_texts` SET `content_loc8` = 'ННЕЕЕЕЕЕЕЕЕтттттттт................!' WHERE `entry` = -478;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ммм, больше колдовства.' WHERE `entry` = -477;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Отец!' WHERE `entry` = -476;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если Рунок вернет его силу, мы все умрем!' WHERE `entry` = -475;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Грязный злоумышленник $R. УМРИ!' WHERE `entry` = -474;
UPDATE `creature_ai_texts` SET `content_loc8` = 'уменьшен до булыжника, но все еще продолжает бороться.' WHERE `entry` = -473;
UPDATE `creature_ai_texts` SET `content_loc8` = 'сила истощается, поскольку куски скалы отламываются.' WHERE `entry` = -472;
UPDATE `creature_ai_texts` SET `content_loc8` = 'начинает раскалываться и ломаться на части.' WHERE `entry` = -471;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы слышали мои слова, я найду применение для вашего тела после того, как я убью Вас, $R.' WHERE `entry` = -470;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы никогда не остановите Брошенного, $R. Темная Леди заставит вас страдать.' WHERE `entry` = -469;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вот и все.' WHERE `entry` = -468;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Крипта!' WHERE `entry` = -467;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы... победили...' WHERE `entry` = -466;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Зверь! Повинуйся! Убей их скорей!' WHERE `entry` = -465;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы будем биться насмерть!' WHERE `entry` = -464;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я быстро разберусь с вами...' WHERE `entry` = -463;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Совет Темнолесья должен принять меры. Зло сохраняется в воздухе.' WHERE `entry` = -462;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Абер? Это - Вы...? О... Я так хочу есть, Абер! Я ТАКОЙ ГОЛОДНЫЙ!!' WHERE `entry` = -461;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Стойте... вы не мой муж. Но он, должно быть, послал Вас. И вы... выглядите.. восхитительно!' WHERE `entry` = -460;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мертвецы ползают по всей площади земли. Где Армия Штормграда?' WHERE `entry` = -459;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Люди Темнолесья надеются на большее от Совета. Мы не можем позволить им страдать от этого безобразного гнева, который изводит нас.' WHERE `entry` = -458;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наши дела не доходят до глухих ушей каменных стен Штормграда.' WHERE `entry` = -457;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я боюсь нечто темное приближается.' WHERE `entry` = -456;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы нуждаемся в лучшей защите от Штормграда. Наши дома захватывают мертвецы.' WHERE `entry` = -455;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Постоянное препирательство не оставит нас нигде. Мы должны принять меры.' WHERE `entry` = -454;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Новости из Штормграда не служат хорошим предзнаменованием....' WHERE `entry` = -453;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Свет кажется оставил нас.' WHERE `entry` = -452;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Почему стража Штормграда не приехали?' WHERE `entry` = -451;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тяжелый труд не в делах прошлого, $N!' WHERE `entry` = -450;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кто этот простой $R, который ворошит в прошлое? Возможно легенда о Сталване умрет вместе с вами!' WHERE `entry` = -449;
UPDATE `creature_ai_texts` SET `content_loc8` = 'издает пронзительный крик.' WHERE `entry` = -448;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Волшебник падет!' WHERE `entry` = -447;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нас не остановят!' WHERE `entry` = -446;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Победа или смерть!' WHERE `entry` = -445;
UPDATE `creature_ai_texts` SET `content_loc8` = 'У вас заканчивается время!' WHERE `entry` = -444;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Расселина должна быть защищена!' WHERE `entry` = -443;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваши усилия... напрасны.' WHERE `entry` = -442;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы не закончили!' WHERE `entry` = -441;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Смерть Последнему Опекуну!' WHERE `entry` = -440;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы не потерпим неудачу!' WHERE `entry` = -439;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы открылись!' WHERE `entry` = -438;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я останусь и буду охранять место крушения. Поспешите! Мы надеемся, никто не заметит дым...' WHERE `entry` = -437;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Похоже вы идете в Кабестан, передайте Пароклапану, что я разрушил шинковку.' WHERE `entry` = -436;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это является примером того, что не надо призывать. Посмотрите, это является хилым и ломким. Один хороший удар булавой разнесет это на черепки и кости.' WHERE `entry` = -435;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я хочу увидеть Башню Волшебника.' WHERE `entry` = -434;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Куда мы направляемся?' WHERE `entry` = -433;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Почему мы всегда идем тем же самым путём?' WHERE `entry` = -432;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это правда? Крокодилы в канале?' WHERE `entry` = -431;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мои ноги повреждены.' WHERE `entry` = -430;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы уже пришли?' WHERE `entry` = -429;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Плеть я говорю сама с собой. Только так я могу побеседовать, хоть с кем-то в этом городе.' WHERE `entry` = -428;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Как будто у меня больше нету других забот, как на старости лет таскать ведра с водой.' WHERE `entry` = -427;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Где вода Эмма? Ты раздобыла воды Эмма? Если бы не было меня, то они бы даже не знали как выглядит вода.' WHERE `entry` = -426;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кажется как будто я хожу по сто раз на дню, по одному и тому же пути, чтобы добыть больше воды. Никакого уважения к их старейшинам, это говорю тебе я.' WHERE `entry` = -425;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Джек и Джилл мои морщинистые задницы! Я перекачаю всю воду отсюда.' WHERE `entry` = -424;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Думаю я разрешу прорыть канал, обложенный булыжником.' WHERE `entry` = -423;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Помните, дети: Вы всегда делаете меньше плохого, чем могли бы. Удвойте это!' WHERE `entry` = -422;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Добавьте только половину в следующий раз.' WHERE `entry` = -421;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тогда добавим вдвое больше в следующий раз!' WHERE `entry` = -420;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сэр, я думал, что мы закончили с Корнем Летаргии в том последнем ядовитом рецепте.' WHERE `entry` = -419;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сэр, наши клиенты жалуются, что в наших анестезирующих средствах содержится слишком много Смертельного Сорняка.' WHERE `entry` = -418;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сэр, наши клиенты жалуются, что в наших Смертельных Ядах недостает Девственных Мучений.' WHERE `entry` = -417;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Внезапно они появились отовсюду.' WHERE `entry` = -416;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Должно быть у них был сообщник, помогающий им.' WHERE `entry` = -415;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если Капитан узнает, то это станет концом для меня.' WHERE `entry` = -414;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это - все их ошибка, глупая армия Альянса. Они просто должны были построить свои башни прямо позади моей фермы.' WHERE `entry` = -413;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Проявите милосердие к бедному слепому?... Вы подразумеваете, что я не слепой?... Я НЕ СЛЕПОЙ! Я МОГУ ВИДЕТЬ! ЧУДО!' WHERE `entry` = -412;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я с удовольствием заплачу вам во вторник, а за гамбургер сегодня.' WHERE `entry` = -411;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Хммм, это похоже на что-то, что можно принять за "перезвон ветра". Возьмите на заметку класс... Это не то, что вы хотели бы вызвать в разгаре сражения.' WHERE `entry` = -410;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Спустите те части к кораблю!' WHERE `entry` = -409;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кто-нибудь хочет отдохнуть? Ясно, очень плохо! Приступайте к работе чурбаны!' WHERE `entry` = -408;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я пролью твою кровь, $C!' WHERE `entry` = -407;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Никогда не пересекайте Темное Железо, $C.' WHERE `entry` = -406;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Зарикотль выглядит спокойней после того как съел останки $N' WHERE `entry` = -405;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я не могу позволить вам войти в храм! Я должен вас уничтожить для вашего же блага!' WHERE `entry` = -404;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Дракондор движется с запада! Стреляйте по друиду внизу!' WHERE `entry` = -403;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не смотрите на демонов. Уничтожение зла сегодня нас не касается.' WHERE `entry` = -402;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Разбить Солнечную нечисть! Огонь по желанию!' WHERE `entry` = -401;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это все что я хотел сказать. Оставайтесь собранными, мальчики и девочки.' WHERE `entry` = -400;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Излишне говорить о том, что многие из нас не вернуться домой. Но если вы вспомните ваши тренировки и удержите их в голове это значительно повысит ваши шансы.' WHERE `entry` = -399;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наша задача в том чтобы очистить как можно больше пищи, также поддержать специалистов силой убеждения от измены.' WHERE `entry` = -398;
UPDATE `creature_ai_texts` SET `content_loc8` = 'На вершине плато, он и его дружки демоны пытаются возродить Солнечный Колодцец и открыть разлом для возвращения их главнокомандующего Кил''джедена обратно в мир.' WHERE `entry` = -397;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Остров Кель''Данас был переполнен силами принца Кель''таса Солнечного Скиталеца. Умники пометили его как умершего. Умники ошиблись.' WHERE `entry` = -396;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Приветствую вас новобранцы. Я Сержант-инструктор Бадум. В ближайшие несколько дней вы все получите оринтеровки.' WHERE `entry` = -395;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я ожидаю ваших распоряжений о особых задачах. В это время стоим здесь и готовы выдвинуться в любой момент!' WHERE `entry` = -394;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Войны должны направится на удержание ключевых позиций, в то время как стрелки закрепляют оборону залива от врагов.' WHERE `entry` = -393;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Люди уверяю вас, что если он преуспеет в этом мире будет страданий многим больше чем когда либо приносило Запределье! Так сделаем же чтобы этого не произошло.' WHERE `entry` = -392;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я знаю мы думали что он мертв, но это не так. Он пытается использовать Плато Солнечного Колодца для вызова  в этот мир мастера Пылающего Легиона Кил''джедена.' WHERE `entry` = -391;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Текущая ситуация выглядит так: мы удерживаем все что нам под силу, а все те кто более опытен и вооружен выдвигаются к Принцу Кель''тасу.' WHERE `entry` = -390;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Добро пожаловать в Плато Солнечного Колодца. Несмотря на мягкий климат и живописные пейзажи, дамы и господа вы не на отдыхе!' WHERE `entry` = -389;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если у кого то из вас дамочки имеются вопросы, вы можете получить дальнейшие указания от лидеров ваших отрядов. Это все.' WHERE `entry` = -387;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы тут как поддержка для так называемых "приключенцев", как говорится призывное начальство. Мы помогаем удерживать ключевые точки острова и сохраняем тепло, так что они могут выполнять свою работу.' WHERE `entry` = -386;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Так а теперь о том что это за путь, добро пожаловать на Остров Кель''Данас. Плато Солнечного Колодца расположено к югу, и принц Кель''тас обитает в Терраса Магистров на востоке.' WHERE `entry` = -385;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Во-первых, хоть ты и послушник син''дорай. Я правлю судном... Это не тоже самое что использование Провидцев. Тяни всем свои весом или возвращайся в лодку!' WHERE `entry` = -384;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Дренеи с некоторыми из вас я стоял против Скеттиса, а с другими в ДолинеПризрачной Луны. Но теперь мы в Азероте и положение дел выглядит мрачно.' WHERE `entry` = -383;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Хорошо, потише. У нас много работы и очень мало времени чтобы пускать это в массы.' WHERE `entry` = -382;
UPDATE `creature_ai_texts` SET `content_loc8` = 'ВНИМАНИЕ!' WHERE `entry` = -381;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пошли прочь, это место наше!' WHERE `entry` = -380;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мое! Вы не должны взять это место!' WHERE `entry` = -379;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Стойка берсерка! Атаковать их без раздумий!' WHERE `entry` = -378;
UPDATE `creature_ai_texts` SET `content_loc8` = '[Орочий] Таго мог регас ги мог Товноказ Кагг' WHERE `entry` = -377;
UPDATE `creature_ai_texts` SET `content_loc8` = '[Орочий] Огг каз ко зугас кил мог Товноказ Кагг' WHERE `entry` = -376;
UPDATE `creature_ai_texts` SET `content_loc8` = 'в тот момент когда динамит начинает светиться, его глаза наливаются кровью и он начинает хохотать как сумашедший!' WHERE `entry` = -375;
UPDATE `creature_ai_texts` SET `content_loc8` = '[Дворвский] Дум мос' WHERE `entry` = -374;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Умри во имя Рагнароса!' WHERE `entry` = -373;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Теперь бухта принадлежит Племени Камнедробов, $N! А сейчас умри!' WHERE `entry` = -372;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Умри $R! Эти земли принадлежат Племени Камнедробов!' WHERE `entry` = -371;
UPDATE `creature_ai_texts` SET `content_loc8` = '$C вызывает $N? Ты приготовь хороший завтрак!' WHERE `entry` = -370;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Разбить это!' WHERE `entry` = -369;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Так $R хорошенько присмотри за едой!' WHERE `entry` = -368;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ха! Как так?' WHERE `entry` = -367;
UPDATE `creature_ai_texts` SET `content_loc8` = 'АРРРРР!' WHERE `entry` = -366;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Помоги мне!' WHERE `entry` = -365;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Бухаха! Я говорил что прикончу тебя!' WHERE `entry` = -364;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тендал Спен предвидел Рагнароса. Итак следуем к строящейся каменной заграде!' WHERE `entry` = -363;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Верховный король Бронзобород дурак и шарлатан!' WHERE `entry` = -362;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Рааар!!! Меня ударил $R!' WHERE `entry` = -361;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я ударю! Ты помрешь!' WHERE `entry` = -360;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я тебя размажу!' WHERE `entry` = -359;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Время умирать $C!' WHERE `entry` = -358;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ощути мощь Дворфов Темного Железа!' WHERE `entry` = -357;
UPDATE `creature_ai_texts` SET `content_loc8` = '$C, слабак! Ты не подходишь Племени Камнедробов!' WHERE `entry` = -356;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Хороший $R это мертвый $R!' WHERE `entry` = -355;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ай! Меня убивают!' WHERE `entry` = -354;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я не стану бежать подобно тебе $C' WHERE `entry` = -353;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это был 200 летний порт Папеллвербос!' WHERE `entry` = -352;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Все было потрачено впустую на тебе подобных!' WHERE `entry` = -351;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Как ты посмел нарушить обед хозяина!' WHERE `entry` = -350;
UPDATE `creature_ai_texts` SET `content_loc8` = 'направляет ослепляющий рой прямо перед собой.' WHERE `entry` = -349;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Теперь ты предстанешь перед Орабусом, дурак!' WHERE `entry` = -348;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кормчий идет к вам!' WHERE `entry` = -347;
UPDATE `creature_ai_texts` SET `content_loc8` = 'зовет подкрепление!' WHERE `entry` = -346;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы идете на поправку.' WHERE `entry` = -345;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Выпей это, это поможет.' WHERE `entry` = -344;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Позвольте мне помочь вам с ними.' WHERE `entry` = -343;
UPDATE `creature_ai_texts` SET `content_loc8` = 'призывает больше своих союзников из теней.' WHERE `entry` = -342;
UPDATE `creature_ai_texts` SET `content_loc8` = 'выпрыгивает из теней!' WHERE `entry` = -341;
UPDATE `creature_ai_texts` SET `content_loc8` = 'изучает информацию на плакате розыска.' WHERE `entry` = -340;
UPDATE `creature_ai_texts` SET `content_loc8` = 'тихий шепот с благоговейной интонацией подчиняющий ее дыханию.' WHERE `entry` = -339;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эхх, другой сильный странник. Ниже может быть опасно, вы наверное хотите получить в свое распоряжение более сильные заклинания. Я вожу реактивы, обычные и экзотические. Подходите, покупайте вы не об этом не пожалеете!' WHERE `entry` = -338;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Здешние создание сильны, путник. Вам потребуется достаточно боеприпасов, если вы хотите выжить. Вам повезло у меня хороший запас стрел, патронов и метательного оружия. Цены приемлемы, учитывая обстоятельства.' WHERE `entry` = -337;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это война и не заблуждайтесь это совсем не обычный бой в нем не победить в одиночку. Если мы не будем сражаться, грызть, рвать, и отвешивать пинки за каждую пядь земли этого расшатанного мира, все будет потеряно.' WHERE `entry` = -336;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сколько еще солдат должно погибнуть прежде чем мы начнем обращать туда свое внимание?' WHERE `entry` = -335;
UPDATE `creature_ai_texts` SET `content_loc8` = 'И что ты думаешь что демоны будут играть в игрушки? Эти чудовища более жестоки чем орки и намного коварнее чем нежить. Не пытайся привлечь Легион к обычным принципам войны.' WHERE `entry` = -334;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я еще ничего не получил! Ты что слепой? На видишь, что демоны стучаться в наши двери? Кто я такой чтобы посылать тебя к твоим дружкам шаманам? Вышвырнуть их вон!' WHERE `entry` = -333;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Брон! Эй Брон! Ау Брон! Ударь меня!' WHERE `entry` = -332;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет, это знакомый зануда. Стукни меня своим молотком!' WHERE `entry` = -331;
UPDATE `creature_ai_texts` SET `content_loc8` = 'ПЕРСТАНЬТЕ СТРОИТЬ ГЛАЗЕНКИ!' WHERE `entry` = -330;
UPDATE `creature_ai_texts` SET `content_loc8` = '...ЭТО БЫЛО ВЕЛИКОЛЕПНО!' WHERE `entry` = -329;
UPDATE `creature_ai_texts` SET `content_loc8` = 'миг, и озадаченное выражение растеклось по его лицу.' WHERE `entry` = -328;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Что с моими кулаками?' WHERE `entry` = -327;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я... не уверен что это хорошая мысль, придурок. Ты же можешь покалечиться...' WHERE `entry` = -326;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ар... Ишак!?' WHERE `entry` = -325;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пора повеселиться!' WHERE `entry` = -324;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Всего листик ганжы изменит восприятие мира' WHERE `entry` = -323;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Листья плохие, так что не обрабатывай их' WHERE `entry` = -322;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я занимаюсь ворами марихуаны у первого колдуна в этом крыле' WHERE `entry` = -321;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пески поглотят тебя!' WHERE `entry` = -320;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Возможно я должен подобрать несколько других агентов и главу среди них после этих перемен?' WHERE `entry` = -319;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Недавно кто то пробовал выходить на сбор даров Нетерлока, все кто вернулся были сжатым слоем смелых авантюристов!' WHERE `entry` = -318;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Остроумие в награду за скидку, как они могли отказаться в понедельник?' WHERE `entry` = -317;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если я увижу здесь слугу лодыря, я посажу его в катапульту и запущу к Черному Храму!' WHERE `entry` = -316;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Постоянно кто то из прислуги хочет отдохнуть, кладбище как раз вон там.' WHERE `entry` = -315;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Проклятые огры. Проклинаю, чтобы они провалились. Никто не придет нас спасать от этих дикарей! Это пятое похищение за многие дни.' WHERE `entry` = -314;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это лучшая награда, которую мы может предложить. Надеемся кто то возьмется за задание.' WHERE `entry` = -313;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Как он это делает?' WHERE `entry` = -312;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Этот немного лучше, чем последний. Однако, этот все еще страдает от той же самой хрупкой структуры кости как и другие. Когда вы мобилизуете одного из них, вы идете правильным путем.' WHERE `entry` = -311;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я хочу быть точно таким, как Питфайтер!' WHERE `entry` = -310;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Он такой дисциплинированный!' WHERE `entry` = -309;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Он победит? Он может победить?' WHERE `entry` = -308;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ого! Посмотрите на эти мускулы!' WHERE `entry` = -307;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Молись своим богам, шаман. Быть может они тебе помогут. Орда, однако, не сможет...' WHERE `entry` = -306;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Глаза у вас есть? Разве вы не видите демонов прямо на вашем пороге? У меня нет лишних солдат в распоряжении!' WHERE `entry` = -305;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вам от меня что то нужно, шаман?' WHERE `entry` = -304;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Согласен, у нас некоторые проблемы. Я думаю это совершенно ясно. Вопрос в том, что нам с ними делать?' WHERE `entry` = -303;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Военнокомандующим назначена награда за голову Араззиуса! Как правило, сейчас этот злобный кусок демона враг номер один.' WHERE `entry` = -302;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Но как, шеф? Я думал что проклятие было снято...' WHERE `entry` = -301;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты ничтожество...' WHERE `entry` = -300;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это какой то орк, лидер?' WHERE `entry` = -299;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я видел гномов за работой потруднее твоей, слуга! Мелкая девчонка гном - с свиным хвостом! ШЕВЕЛИСЬ, ШЕВЕЛИСЬ, ШЕВЕЛИСЬ!' WHERE `entry` = -298;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваша болтушка готова. Подойдите, заберите ее...' WHERE `entry` = -297;
UPDATE `creature_ai_texts` SET `content_loc8` = 'И если я услышу, что вы глупцы снова пожалуетесь Назгрелу, то в следующий раз приготовлю одного из вас...' WHERE `entry` = -296;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если бы мой живот не угрожал бы отделится от моего тела и убежать от того что мы даем заключенным, то я внаверное был бы оскорблен этим... это еда.' WHERE `entry` = -295;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я чувствую привкус корицы? Или это мускат? Что бы то ни было, в одном я уверен - никто не готовит осла и пченье лучше вас.' WHERE `entry` = -294;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Так мы там были - я и батальон, производя рутинную разведку низа дороги кости. Мы послали разведчика вперед осмотреться вокруг на случай приближения опасности.' WHERE `entry` = -293;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Действительно, разведчик вернулся назад в спешке, говорил что встретил нескольких орков в нижнем проходе. Как мы и полагали они не заметили что мы идем за знатоком.' WHERE `entry` = -292;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Большие красные ублюдки! Больше любого орка которого я когда либо видел. Мускулы вооот такие, клыки воот до сюда...' WHERE `entry` = -291;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Желчь орков...' WHERE `entry` = -290;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я не знаю, хрюкание. Я просто - не сделал - знаю...' WHERE `entry` = -289;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Но это не самое плохое. Прежде чем я смог вытащить нас назад, их группа обнаружила нас и напала.' WHERE `entry` = -288;
UPDATE `creature_ai_texts` SET `content_loc8` = 'В этот день потеряны несколько моих лучших солдат...' WHERE `entry` = -287;
UPDATE `creature_ai_texts` SET `content_loc8` = 'кивок' WHERE `entry` = -286;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Та Наару, вожможно так.' WHERE `entry` = -285;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Благословите нашу терпимость к эльфийским посетителям.' WHERE `entry` = -284;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Продлите это благословление на наш древний дом, мы молим.' WHERE `entry` = -283;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пожалуйста благослови и защити их, и предоставь им одержать верх над теми кто стремится причинить нам вред...' WHERE `entry` = -282;
UPDATE `creature_ai_texts` SET `content_loc8` = 'В нашей борьбе против тьмы мы послали наших детей.' WHERE `entry` = -281;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Свет, охватывающий нас, мы молим тебя...' WHERE `entry` = -280;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Друзья мои, пожалуйста, присоединяйтесь к моей скромной мольбе Свету.' WHERE `entry` = -279;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Благородная просьба. Это было бы честью, Эротем.' WHERE `entry` = -278;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Конечно, друг мой. Чем я могу послужить вам?' WHERE `entry` = -277;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Возможно так и есть.' WHERE `entry` = -276;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы только что отослали другую неопытную команду в Награнд. Могли бы вы просить вознести молитву для них?' WHERE `entry` = -275;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Отшельник Ниндамен у меня к вам просьба.' WHERE `entry` = -274;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Возможно так и есть.' WHERE `entry` = -273;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Булки у меня прямо здесь. Подвиньтесь!' WHERE `entry` = -272;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да, да, я булочник. Знаете почему? Потому что я продаю булки, вот почему!' WHERE `entry` = -271;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Согласитесь, эта точка поражает. Булки на продажу! Получите свои свежие булки прямо звесь!' WHERE `entry` = -270;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кроме полной пивной кружки ничего лучше не подоидет под мои великолепные булки.' WHERE `entry` = -269;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Грок разозлится если хиляки не пойдут к Реблистому Лезвию для разговора с Могдоргом!' WHERE `entry` = -268;
UPDATE `creature_ai_texts` SET `content_loc8` = 'ТОРГОВЕЦ ФРУКТАМИ!!! Твоя повозка все еще не прибыла к нам! Мы дает тебе один час чтобы доставить ее к нам. Не проверяй больше наше терпение!' WHERE `entry` = -267;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я голоден. Фрукты выглядят вкусно.' WHERE `entry` = -266;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы выглядите томящимся от любви. Ya выглядят томящимися от любви. Кто то особенный ожидает вас там а? Не беспокойтесь, не беспокойтесь. Вы получите от меня этот медальон, будете носить и когда вас увидит она то на веки вечные вы для нее станете возлюбленным!' WHERE `entry` = -265;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я чувствую быстрое приближение войны. Торговец фруктами нанял себе в помощь огра. Я должен тоже нанять хорошего помощьника.' WHERE `entry` = -264;
UPDATE `creature_ai_texts` SET `content_loc8` = 'О чем может кричать бедный орк? Кто то должен увидеть что происходит.' WHERE `entry` = -263;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы выглядите устало, $c. У меня есть нечто для вас. Эти амулеты, они могут помочь вам перепрыгивать препятствия и плавать через реки как будто вы были рождены для этого. Они улучшают вкус пищи которую вы едите. Заживляют раны прямо на глазах!' WHERE `entry` = -262;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Клан Блейдспайр не сражается честно. Чтобы помочь партии, нужен Гронн. Отправляйтесь к Горам Ребристого Лезвия поговорите с Морщинистым Могдоргом. Прикончите Громма.' WHERE `entry` = -261;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Морщинистый Могдорг сказал Гроку идти в город к Блудмаулу за помощью. Грок пошел.' WHERE `entry` = -260;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Гроку нужна помощь! Почему никто не помогает?' WHERE `entry` = -259;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эй! Эй, $r! У меня имеется вещичка исключительно для вас. Вы когда-нибудь встречали Тикбалангов? Страшный создания. Способные утащить вас на расстоянии. Что вам необходимо так это мои тикбаланг обереги. Гарантированно оберегают от всех тикбалангов в круге!' WHERE `entry` = -258;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Посмотрите сюда, $c! У меня есть нечто для вас. Исключительно то что вам нужно. Это мыло, верно... и оно на веревочке! Без обиды, но вы немного готовы, вы знаете о чем я говорю? ' WHERE `entry` = -257;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если никто не поможет. Грок размажет!' WHERE `entry` = -256;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Могу поклясться, у меня было больше яблок. Грок!' WHERE `entry` = -255;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Удивительные Амулеты! Невероятно редкие! Нововведение в производстве драгоценностей не имеющее аналогов в действующих мистических методах Грифтаха! Сделайте себя лучше этими волшебными амулетами по приемлемым ценам!' WHERE `entry` = -254;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Там, внутри опасно? Знаете что вам нужно? Защита. Я могу вам помочь избежать смерти! Вы носите этот безумный камень на шее, видите, и тогда вы сможете вернуться назад, если найдете себя в миру духов! Просто быстрая веселая прогулка к вашему трупу и вы снова здесь.' WHERE `entry` = -253;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Подойди простачек, $r. Не хотите рисковать собой там в подземелье, понимаете меня? Грязная работа... и ради чего? Нескольких ничего не стоящих побрякушек? Нет то что вам необходимо это один из моих амулетов. Работает даю гарантирую! ' WHERE `entry` = -252;
UPDATE `creature_ai_texts` SET `content_loc8` = 'слабаки' WHERE `entry` = -251;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Учись читать жаждущий дела. Тост, а?' WHERE `entry` = -250;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Отправьте это!' WHERE `entry` = -249;
UPDATE `creature_ai_texts` SET `content_loc8` = 'У меня и в мыслях небыло что это станет маслом манны! Там ходят многие кому это требуется, за исключением Грека конечно!' WHERE `entry` = -248;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Грек получил напиток' WHERE `entry` = -247;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это масло не достойно Грека! Что Грек нашел такого в тебе? Быть может у него слабость к мантиям? ' WHERE `entry` = -246;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Грек пытается!' WHERE `entry` = -245;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кто-нибудь из прибывших прочтите этот плакат о розыске Грека. Грек не умеет читать.' WHERE `entry` = -244;
UPDATE `creature_ai_texts` SET `content_loc8` = 'За свое высокомерие ты умрешь друид!' WHERE `entry` = -243;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты осмелился побеспокоить преданных последователей Ворона?' WHERE `entry` = -242;
UPDATE `creature_ai_texts` SET `content_loc8` = 'За свое высокомерие ты умрешь друид!' WHERE `entry` = -241;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты осмелился побеспокоить преданных последователей Ворона?' WHERE `entry` = -240;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Время Ворона ночь, но ты закончишь здесь!' WHERE `entry` = -239;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Дурачье! Сущность ястреба никогда не будет вашей!' WHERE `entry` = -238;
UPDATE `creature_ai_texts` SET `content_loc8` = 'сосредоточивается на $N.' WHERE `entry` = -237;
UPDATE `creature_ai_texts` SET `content_loc8` = 'она обнажает свои клыки и угрожающе шипит на окружающих.' WHERE `entry` = -236;
UPDATE `creature_ai_texts` SET `content_loc8` = 'его плоть разбивается в неземной ярости!' WHERE `entry` = -235;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Взбешенные ветра окружают Ваккиза по мере того как он угрожающе продвигается в вашу сторону.' WHERE `entry` = -234;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Столько дел, столько нужно сделать! Куда девается время?' WHERE `entry` = -233;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Такое насекомое Братству не помеха.' WHERE `entry` = -232;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я тебя порешу!' WHERE `entry` = -231;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Скоро ты будешь мертв!' WHERE `entry` = -230;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Убить тебя будет не сложно.' WHERE `entry` = -229;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я скручу тебя в косяк!' WHERE `entry` = -228;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да запылают небо и земля!' WHERE `entry` = -227;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пусть прольется огненный дождь!' WHERE `entry` = -226;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сладких снов...' WHERE `entry` = -225;
UPDATE `creature_ai_texts` SET `content_loc8` = 'У тебя усталый вид...' WHERE `entry` = -224;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мор и гибель на вас!' WHERE `entry` = -223;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Рой хочет есть!' WHERE `entry` = -222;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Часы... еще... идут.' WHERE `entry` = -221;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы смертные умираете слишком быстро!' WHERE `entry` = -220;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Крикни в последний раз!' WHERE `entry` = -219;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Надежда умирает последней!' WHERE `entry` = -218;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мир, который вы защищаете обречен! Бегите прочь и быть может вы продлите свои жалкие жизни!' WHERE `entry` = -217;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Все ваши усилия были напрасны, ибо Древо Жизни уже иссыхает! Скоро, сердце вашего мира перестанет биться!' WHERE `entry` = -216;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Разрушать!' WHERE `entry` = -215;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Убивать!' WHERE `entry` = -214;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Крошить!' WHERE `entry` = -213;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Аааггггг!' WHERE `entry` = -212;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Умри во имя Эдвина Ван Клифа' WHERE `entry` = -211;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я доставлю тебя, слабый $C, в мир иной!' WHERE `entry` = -210;
UPDATE `creature_ai_texts` SET `content_loc8` = 'У меня есть специальное сообщение для $N. И в нем сказано что Вы должны умереть!' WHERE `entry` = -209;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мелочь?' WHERE `entry` = -208;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Поможешь бедному бомжу?' WHERE `entry` = -207;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Лоск для медной брони?' WHERE `entry` = -206;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Продаю свежевыпеченый хлеб!' WHERE `entry` = -205;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Продаю свежий хлеб!' WHERE `entry` = -204;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ма рес бромо зольн килагрин дра ма зоерн ту ко фрат ка тадром Ма крин дринор зальн дирнор Ма крин кан аасругель корсул' WHERE `entry` = -203;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Из твоей головы выдет отличный троффей, $R.' WHERE `entry` = -202;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мои когти порвут на части твое тельце, $R.' WHERE `entry` = -201;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты будешь лёгкой добычей, $C.' WHERE `entry` = -200;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Страдай, презренный червяк!' WHERE `entry` = -199;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Никого не осталось проверить меня!?' WHERE `entry` = -197;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Твои дни сочтены!' WHERE `entry` = -196;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Твоё время выходит!' WHERE `entry` = -195;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тёмный Властелин смеётся над вами!' WHERE `entry` = -194;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы ничто, я отвечаю более высоким требованиям!' WHERE `entry` = -193;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы сталкивались во многих схватках, жаль, они все были напрасными. Скоро ваши люди преклонят колени пред моим лордом!' WHERE `entry` = -192;
UPDATE `creature_ai_texts` SET `content_loc8` = '...сгинь на вечно!' WHERE `entry` = -191;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Взрывы! БОЛЬШЕ взрывов! Еще больше взрывов!' WHERE `entry` = -190;
UPDATE `creature_ai_texts` SET `content_loc8` = 'За моими машинами будущее! Они всех вас уничтожат!' WHERE `entry` = -189;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ах вы захватчики!!! Гномереган мой!!!' WHERE `entry` = -188;
UPDATE `creature_ai_texts` SET `content_loc8` = 'вызывает своих воргов!' WHERE `entry` = -187;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Живые здесь!' WHERE `entry` = -186;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Признайтесь и мы освободим Вас.' WHERE `entry` = -185;
UPDATE `creature_ai_texts` SET `content_loc8` = 'В конечном счете ты заговоришь. Также теперь ты мог бы это пролить.' WHERE `entry` = -184;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Что? О нет. Меня не волнует что вы должны сказать. Я только люблю причинять боль.' WHERE `entry` = -183;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мой! Мой! Мой! Гизлок - правитель этой области! Вы никогда не должны показывать мое присутствие!' WHERE `entry` = -182;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мы настоящая Орда!' WHERE `entry` = -181;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мои питомцы голодны и они поужинают вашей плотью!' WHERE `entry` = -180;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Придержите их пока я выпускаю боевых гончих!' WHERE `entry` = -179;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сапоги? Ты сможешь снять их только с моего мертвого холодного... ар... РАГР!' WHERE `entry` = -178;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я собираюсь носить твою кожу вместо пиджака!' WHERE `entry` = -177;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы начинаете меня злить!' WHERE `entry` = -176;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Салаги вы крепче чем я думал! Придется импровизировать!' WHERE `entry` = -175;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нас атакуют! Вперед швабры лохматые! Сметем захватчиков!' WHERE `entry` = -174;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Братство победит!' WHERE `entry` = -173;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Глупцы! Мы боримся за правое дело!' WHERE `entry` = -172;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Все вы трусливые псы!' WHERE `entry` = -171;
UPDATE `creature_ai_texts` SET `content_loc8` = 'туда тебе и дорога!' WHERE `entry` = -170;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Никто не смеет бросить вызов братству!' WHERE `entry` = -169;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ох подходи! Позволь не драться!' WHERE `entry` = -168;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваша смерть будет мучительной.' WHERE `entry` = -162;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Молите о пощаде! Я положу конец вашему бессмысленному существованию.' WHERE `entry` = -161;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Этот мир НАШ!' WHERE `entry` = -160;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Локтар Иллидари!' WHERE `entry` = -159;
UPDATE `creature_ai_texts` SET `content_loc8` = 'За Каргата! За победу!' WHERE `entry` = -158;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Лок Нараш!' WHERE `entry` = -157;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Кровь наша сила!' WHERE `entry` = -156;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Начинай вооружаться Бомбой Близости!' WHERE `entry` = -155;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Иллидан господствует!' WHERE `entry` = -154;
UPDATE `creature_ai_texts` SET `content_loc8` = 'сила увядает!' WHERE `entry` = -153;
UPDATE `creature_ai_texts` SET `content_loc8` = '$N увеличивается в размере!' WHERE `entry` = -152;
UPDATE `creature_ai_texts` SET `content_loc8` = 'впадает в ярость!' WHERE `entry` = -151;
UPDATE `creature_ai_texts` SET `content_loc8` = 'начинает читать заклинание общего исцеление!' WHERE `entry` = -150;
UPDATE `creature_ai_texts` SET `content_loc8` = 'входит в транс!' WHERE `entry` = -149;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вау! Спасибо!' WHERE `entry` = -148;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты боишься смерти?' WHERE `entry` = -147;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эту часть я люблю больше всего.' WHERE `entry` = -146;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не становись самонадаеянным... смертный.' WHERE `entry` = -145;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наконец! Что то для развеивания скуки!' WHERE `entry` = -144;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я сломлю тебя!' WHERE `entry` = -143;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Жалкий смертный! Ты дорого заплатишь!' WHERE `entry` = -142;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нарушители! Включить тревогу!' WHERE `entry` = -141;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Жернова смерти... раздавят тебя.' WHERE `entry` = -140;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Придите ко мне, братья!' WHERE `entry` = -139;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мне надоело тратить на вас время!' WHERE `entry` = -138;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не ной!' WHERE `entry` = -137;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ничего у тебя не вышло!' WHERE `entry` = -136;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пируйте, братья мои!' WHERE `entry` = -135;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вам не... победить... мой дух!' WHERE `entry` = -134;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я охотник! Вы добыча...' WHERE `entry` = -133;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы выиграли битву... но... не войну.' WHERE `entry` = -132;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Победа Легиону!' WHERE `entry` = -131;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Смерть всему живому!' WHERE `entry` = -130;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пепел к пеплу, прах к праху.' WHERE `entry` = -129;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Умри и разлагайся!' WHERE `entry` = -128;
UPDATE `creature_ai_texts` SET `content_loc8` = 'В могиле будет намного холоднее.' WHERE `entry` = -127;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Покарись ледяному дыханию... смерти!' WHERE `entry` = -126;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Начался последний решающий поход Легиона! Еще немного и мы поработим этот мир, не щадите никого!' WHERE `entry` = -125;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наглость!' WHERE `entry` = -124;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я король змей! Я кое что могу.' WHERE `entry` = -123;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не сопротивляйся.' WHERE `entry` = -122;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваше время скоро... истечет.' WHERE `entry` = -121;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тебя ничто не спасет' WHERE `entry` = -120;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Теперь ты чувствуешь, что тебя ожидает.' WHERE `entry` = -119;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Риш, хокта!' WHERE `entry` = -118;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Оставьте надежду! Легион вернулся, чтобы завершить то, что было начато много лет назад. На этот раз спасения не будет!' WHERE `entry` = -117;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Чего хорошего принесло это насилие? То, что сделано, сделано. Я подвел своих людей.' WHERE `entry` = -116;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Разве вы не причинили достаточно вреда? Вы должны нарушить и мою дремоту?' WHERE `entry` = -115;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я не могу выдержать боль. Я должен найти новый источник.' WHERE `entry` = -114;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Больше, больше, больше! Я должен скоро наесться.' WHERE `entry` = -113;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Теперь ваш мир принадлежит нам.' WHERE `entry` = -112;
UPDATE `creature_ai_texts` SET `content_loc8` = 'взрывы забрасывают область тайным осадком!' WHERE `entry` = -111;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наберитесь храбрости! Ваши друзья не будут долго оплакивать вашу смерть!' WHERE `entry` = -110;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Поддержите Закон!' WHERE `entry` = -109;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Служите во имя Общей Веры!' WHERE `entry` = -108;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Защитите невинного!' WHERE `entry` = -107;
UPDATE `creature_ai_texts` SET `content_loc8` = 'приходит в ярость!' WHERE `entry` = -106;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ваши кости сломаются под моими ногами, $R!' WHERE `entry` = -105;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эта земля принадлежит Дворфам из клана Черного Железа. Приготовьтесь увидеть загробную жизнь, $C!' WHERE `entry` = -104;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мозги...' WHERE `entry` = -103;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да здравствует Драконья Пасть! Умри, никчемный $R!' WHERE `entry` = -102;
UPDATE `creature_ai_texts` SET `content_loc8` = 'За клан Драконьей Пасти!' WHERE `entry` = -101;
UPDATE `creature_ai_texts` SET `content_loc8` = 'кричит во все горло, зовя на помощь!' WHERE `entry` = -100;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты никогда не разбудишь мечтателя!' WHERE `entry` = -99;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я... Это заслужил.' WHERE `entry` = -98;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тебе не следовало приходить.' WHERE `entry` = -97;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Увы это было необходимо.' WHERE `entry` = -96;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не заставляйте меня вас убивать.' WHERE `entry` = -95;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы сами напросились!' WHERE `entry` = -94;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Работа должна продолжаться.' WHERE `entry` = -93;
UPDATE `creature_ai_texts` SET `content_loc8` = 'А я ведь вас предупреждал!' WHERE `entry` = -92;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы уверены что сможете мне что-нибудь сделать? Думаете я вас боюсь?!' WHERE `entry` = -91;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Давайте покажите на что вы способны. Уверен что справлюсь одной левой!' WHERE `entry` = -90;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Браво!' WHERE `entry` = -89;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Хмм, я хорош!' WHERE `entry` = -88;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Уходите пока целы.' WHERE `entry` = -87;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я предвижу чью-то мучительную смерть.' WHERE `entry` = -86;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Если мои расчеты не врут, вы должны быть уже мертвы.' WHERE `entry` = -85;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Семь раз отмерь, один отрежь.' WHERE `entry` = -84;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это не предвиденная... случайность.' WHERE `entry` = -83;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да, таков единственный логический исход.' WHERE `entry` = -82;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Твоя стратегия была не безупречна.' WHERE `entry` = -81;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я порежу тебя на куски!' WHERE `entry` = -80;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Получайте Смерч!' WHERE `entry` = -79;
UPDATE `creature_ai_texts` SET `content_loc8` = 'О... это то что нужно.' WHERE `entry` = -78;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Оххх... Это намного лучше.' WHERE `entry` = -77;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вот теперь вы на самом деле меня... разозлили...' WHERE `entry` = -76;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Надо лучше выбирать противников.' WHERE `entry` = -75;
UPDATE `creature_ai_texts` SET `content_loc8` = 'От тебя никакого толку. Как и от одного моего знакомого.' WHERE `entry` = -74;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Неразумно злить меня.' WHERE `entry` = -73;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты добьешься успеха только в познании себя!' WHERE `entry` = -72;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Повернись спиной когда сможешь!' WHERE `entry` = -71;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это... ничего не изменит. Вечное проклятие ждет тебя!' WHERE `entry` = -70;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Другие займут мое место!' WHERE `entry` = -69;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Такая судьба ждет всех, кто посмеет воровать у мастера.' WHERE `entry` = -68;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Для типов как ты, смерть - это милосердие.' WHERE `entry` = -67;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пора выдвигаться...' WHERE `entry` = -66;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Свободен... наконец то.' WHERE `entry` = -65;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это действительно закончено?' WHERE `entry` = -64;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Все... возвращаются ко мне.' WHERE `entry` = -63;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да... думаю теперь, я вспомнил...' WHERE `entry` = -62;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я пропустил показ!' WHERE `entry` = -61;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Они засыпают позже. Что же касается меня, я ложусь вовремя...' WHERE `entry` = -60;
UPDATE `creature_ai_texts` SET `content_loc8` = 'У нас есть так много забав!' WHERE `entry` = -59;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Он спрашивал может ли имп стать соратником... Можешь в это поверить? Вообще-то это было бы полбеды...' WHERE `entry` = -58;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Итак я сказал "Да, но это за дополнительную стоимость"' WHERE `entry` = -57;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пять секунд! Я не шучу!' WHERE `entry` = -56;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты будешь наказан!' WHERE `entry` = -55;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты... Должен... Заплатить...' WHERE `entry` = -54;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Что происходит?' WHERE `entry` = -53;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Где я? Что...' WHERE `entry` = -52;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Судьба повернулась против меня!' WHERE `entry` = -51;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет... ложь...' WHERE `entry` = -50;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет подожди! НЕТ!' WHERE `entry` = -49;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ты обнаружен оком Гриллока!' WHERE `entry` = -48;
UPDATE `creature_ai_texts` SET `content_loc8` = 'бежит прочь в страхе!' WHERE `entry` = -47;
UPDATE `creature_ai_texts` SET `content_loc8` = 'становится злым!' WHERE `entry` = -46;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Мастер... будет зол...' WHERE `entry` = -45;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я закончил!' WHERE `entry` = -44;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Нет!' WHERE `entry` = -43;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Время, чтобы присоединиться к нам $C.' WHERE `entry` = -42;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Что-то должно случится...' WHERE `entry` = -41;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Это конец?' WHERE `entry` = -40;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Стража! Вперед! Убейте их!' WHERE `entry` = -39;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Бандор шореларан!' WHERE `entry` = -38;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Сейчас вы поймете с кем имеете дело.' WHERE `entry` = -37;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я еще... не начила...' WHERE `entry` = -36;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Хватит ныть.' WHERE `entry` = -35;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Идите же ко мне! Я окажу вам достойный прием.' WHERE `entry` = -34;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Пустота... зовет.' WHERE `entry` = -33;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Жизненная... сила... кончилась.' WHERE `entry` = -32;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Этот сосуд... пуст.' WHERE `entry` = -31;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Тень... поглотит вас.' WHERE `entry` = -30;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Жизненная сила... пища' WHERE `entry` = -29;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Вы пришли убить Даллию? А мне можно посмотреть?' WHERE `entry` = -28;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наконец-то я знаю на кого обрушить свой гнев!' WHERE `entry` = -27;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Да, это было не плохо.' WHERE `entry` = -26;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я знал... это единственный выход.' WHERE `entry` = -25;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Защишайтесь, и пусть вам повезет...' WHERE `entry` = -24;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Берегись!' WHERE `entry` = -23;
UPDATE `creature_ai_texts` SET `content_loc8` = 'ВанКлиф хорошо заплатит за ваши головы!' WHERE `entry` = -22;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Образцы... нужно... сохранить.' WHERE `entry` = -21;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Твой жизненный цикл закончен!' WHERE `entry` = -20;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Эндорел Аллюминор!' WHERE `entry` = -19;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Природа покорна моей воли!' WHERE `entry` = -18;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Что вы делаете? Эти образцы очень хрупкие!' WHERE `entry` = -17;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Далеко вам... не пройти' WHERE `entry` = -16;
UPDATE `creature_ai_texts` SET `content_loc8` = 'А ведь я тебя предупреждал...' WHERE `entry` = -15;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я заберу твою жизнь!' WHERE `entry` = -14;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Ищешь награду? А найдешь, лишь смерть!' WHERE `entry` = -13;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я упиваюсь твоей болью!' WHERE `entry` = -12;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я испепелю вас!' WHERE `entry` = -11;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Верещите в огне!' WHERE `entry` = -10;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Незванные гости? Вы умрете!' WHERE `entry` = -9;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Айй! Моя бежать!' WHERE `entry` = -8;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Не трогай свечу!' WHERE `entry` = -7;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Гр-р-р-р… Свежее мясо!' WHERE `entry` = -6;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Будет чьи кости поглодать…' WHERE `entry` = -5;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Почувствуй силу Братства!' WHERE `entry` = -4;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Наконец-то я смогу пустить свой клинок в дело!' WHERE `entry` = -3;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Братство этого так не оставит.' WHERE `entry` = -2;
UPDATE `creature_ai_texts` SET `content_loc8` = 'Я смотрю, эти дураки из Аббатства прислали нам свежего мяса.' WHERE `entry` = -1;

UPDATE `creature_ai_texts` SET `content_default` = '' WHERE `content_default` = NULL;
UPDATE `creature_ai_texts` SET `content_loc1` = NULL WHERE `content_loc1` = '';
UPDATE `creature_ai_texts` SET `content_loc8` = NULL WHERE `content_loc8` = '';

ALTER TABLE `creature_ai_texts` ORDER BY `entry`;

CREATE TABLE IF NOT EXISTS `rus_udb_rev` (
  `name` varchar(50) NOT NULL,
  `value` int(11) unsigned NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DELETE FROM `rus_udb_rev` WHERE `name` = 'creature_ai_texts';
INSERT INTO `rus_udb_rev` (`name`, `value`) VALUES ('creature_ai_texts', '27');
